GENERAL:
  manual_seed: 3407
  tag: default
  gpu: '1'                
  debug: False
  distribute: False
  training_stage: burn_in  # burn_in, or semi
PATH:
  root_path: '/workspace/yf/projects/Semi-SPS'
  scannet_data_folder: '/workspace/yf/projects/Semi-SPS/data/scannet/scannet_data'
  scanref_data_root: '/workspace/yf/projects/Semi-SPS/data'

DATA:
  dataset: ScanRefer
  num_points: 40000
  num_scenes: -1          # default -1 means all scenes
  num_classes: 20
  num_labeled_scenes: 26  # 1% - 6; 5% - 28; 10% - 56; 20% - 124; 30% - 168; NR3D: 10% 52, 5% 26, 1% 6
  random_scenes: False
  use_augment: True       # data augmentation
  max_num_obj: 128

  # input
  use_height: False
  use_color: True
  use_normal: True
  use_multiview: True
  fuse_multi_mode: late   # early or late

  # label
  det_class_label: main_with_others    # all, main_with_others, main

  # scene list of labeled dataset
  labeled_sample_list: scannetv2_train_0.1.txt

MODEL:
  # general
  dropout: 0.1
  use_checkpoint: False

  # EMA paremeter
  alpha: 0.9996

  # Pseudo labels Filtering precision
  filtering_precision: 0.0
  score_thr: 0.08
  alpha_thr: 0.9996
  mu: 0.09       # 0.09 best
  sigma: 0.015   # 0.015
  weighting_mode: soft_weighting # not_weighting, dynamic_threshold, linear_weighting, soft_weighting
  update_mu_sigma: False
  use_jointly_filtering: False
  obj_thr: 0.05
  size_thr: 0.1
  use_nms: True

  # point backbone
  point_feat_dim: 288

  # visual feature
  vis_feat_dim: 128
  
  # sampling
  sampling: kpsa-lang-filter
  num_proposal: 512
  kps_fusion_dim: 256
  use_context_label: False
  ref_use_obj_mask: True
  
  # Head
  size_cls_agnostic: False
  use_objectness: True

  # Language Module
  lang_emb_type: clip
  max_des_len: 77
  word_erase: 0.1
  #embedding_size: 300
  #gru_hidden_size: 256
  #gru_num_layer: 1
  #use_bidir: False # bi-directional GRU

  # Transformer
  model: 'TransformerFilter'
  num_decoder_layers: 5
  object_position_embedding: loc_learned
  point_position_embedding: xyz_learned
  lang_position_embedding: none
  transformer_feat_dim: 384
  ffn_dim: 2048
  n_head: 4
  transformer_dropout: 0.05
  use_ref_mask: False
  use_att_score: True
  ref_filter_steps: [1,2,3,4]
  ref_mask_scale: 0.5
  transformer_mode: serial

  # pretrain
  use_pretrained: True
  pretrain_path: '/workspace/yf/projects/Semi-SPS/data/pretrained_pointnet/xyz_rgb_norm_backbone.pth' # PointNet++
  trans_pre_model: False

LOSS:
  # ----- Refer -----
  use_ref_score_loss: False # labeled kps reference loss
  no_detection: False
  no_reference: False
  no_lang_cls: True
  ref_each_stage: True
  cls_each_stage: True
  ref_criterion: rank
  use_each_stage_box: False
  distill_each_stage: True
  # ----- Detection -----
  kps_topk: 5
  kps_loss_weight: 0.8
  det_loss_weight: 5
  ref_loss_weight: 0.3
  att_loss_weight: 1
  center_delta: 0.04
  size_delta: 0.111111111111
  heading_delta: 1
  # ----- Ablation -----
  consistency_loss_ex: False # when it's true, it won't filter pseudo labels
  use_det_loss: True
  use_att_consistency_loss: True
  use_obj_consistency_loss: True
  use_dks_consistency_loss: False
  use_ref_consistency_loss: True

TRAIN:
  batch_size: 32
  num_workers: 0
  epoch: 32 # 32, 12

  lr: 0.001 # default 0.001
  decoder_lr: 0.0001
  det_decoder_lr: False
  lr_decay_step: [16,24,28] #[16, 24, 28],[10]
  lr_decay_rate: 0.1
  bn_decay_step: 10
  bn_decay_rate: 0.1
  bn_momentum_init: 0.2
  bn_momentum_min: 0.001
  wd: 0.0005

  verbose: 20       # iter num to output log in shell
  val_freq: 2       # epoch num to val
  eval_det: True
  eval_ref: True
  iou_ref_th: 0.25
  iou_ref_topk : 4

  use_10p_model: True